name: Group Stage Scrap Scheduler

on:
  schedule:
    - cron: '36 20 * * 0-6'
    - cron: '38 21 * * 0-6'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.0
      - name: Install NPM
        run: |
          npm install
      - name: Run Group Scraping Task
        run: |
          npm run scrap-group-stage
