name: Cron Scheduler to Scrap Group Stage Results

on:
  push:
    branches:
      - erik/improve-server-stuff

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.0
      - name: Install NPM
        run: |
          npm install
      - name: Run Group Scraping Task
        run: |
          npm run scrap-group-stage
