name: Group Stage Scrap Scheduler

on:
  schedule:
    # Nov 20-28, after matches 11h, 14h, 17h, 20h
    - cron: '50 12 20-28 11 *'
    - cron: '55 12 20-28 11 *'
    - cron: '*/10 13-14 20-28 11 *'

    - cron: '50 15 20-28 11 *'
    - cron: '55 15 20-28 11 *'
    - cron: '*/10 16-17 20-28 11 *'

    - cron: '50 18 20-28 11 *'
    - cron: '55 18 20-28 11 *'
    - cron: '*/10 19-20 20-28 11 *'

    - cron: '50 21 20-28 11 *'
    - cron: '55 21 20-28 11 *'
    - cron: '*/10 22-23 20-28 11 *'

    # Nov 29-30, after matches 16h, 20h
    - cron: '50 17 29-30 11 *'
    - cron: '55 17 29-30 11 *'
    - cron: '*/10 18-19 29-30 11 *'

    - cron: '50 21 29-30 11 *'
    - cron: '55 21 29-30 11 *'
    - cron: '*/10 22-23 29-30 11 *'

    # Dec 1-2, after matches 16h, 20h
    - cron: '50 17 1-2 12 *'
    - cron: '55 17 1-2 12 *'
    - cron: '*/10 18-19 1-2 12 *'

    - cron: '50 21 1-2 12 *'
    - cron: '55 21 1-2 12 *'
    - cron: '*/10 22-23 1-2 12 *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.0
      - name: Install NPM
        run: |
          npm install
      - name: Run Group Scraping Task
        run: |
          npm run scrap-group-stage
