name: Group Stage Scrap Scheduler

on:
  schedule:
    # Nov 20-28, UTC time after matches 11h, 14h, 17h, 20h
    - cron: '50 11 20-28 11 *'
    - cron: '55 11 20-28 11 *'
    - cron: '*/10 12-13 20-28 11 *'

    - cron: '50 14 20-28 11 *'
    - cron: '55 14 20-28 11 *'
    - cron: '*/10 15-16 20-28 11 *'

    - cron: '50 17 20-28 11 *'
    - cron: '55 17 20-28 11 *'
    - cron: '*/10 18-19 20-28 11 *'

    - cron: '50 20 20-28 11 *'
    - cron: '55 20 20-28 11 *'
    - cron: '*/10 21-22 20-28 11 *'

    # Nov 29-30, UTC time after matches 16h, 20h
    - cron: '50 16 29-30 11 *'
    - cron: '55 16 29-30 11 *'
    - cron: '*/10 17-18 29-30 11 *'

    - cron: '50 20 29-30 11 *'
    - cron: '55 20 29-30 11 *'
    - cron: '*/10 21-22 29-30 11 *'

    # Dec 1-2, UTC time after matches 16h, 20h
    - cron: '50 16 1-2 12 *'
    - cron: '55 16 1-2 12 *'
    - cron: '*/10 17-18 1-2 12 *'

    - cron: '50 20 1-2 12 *'
    - cron: '55 20 1-2 12 *'
    - cron: '*/10 21-22 1-2 12 *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.0
      - name: Install NPM
        run: |
          npm install
      - name: Run Group Scraping Task
        run: |
          npm run scrap-group-stage
